version: '3.4'

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/Dockerfile.nginx
    depends_on:
      - django
    volumes:
      - ./static:/srv/web/static:ro
    ports:
      - "80:9000"

  django:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file: .env
    depends_on:
      - db
      - memcached
      - rabbitmq
    command: "/bin/bash /srv/web/start.sh"
    volumes:
      - ./:/srv/web:rw,cached

  db:
    image: postgres:14-alpine
    env_file:
      - 'docker/db/.env'
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine

  memcached:
    image: memcached:alpine3.15

volumes:
  db-data: { }
  redis_data: { }
