version: '3.4'

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/Dockerfile.nginx
    depends_on:
      - django
    volumes:
      - ./static:/srv/web/static:ro
    ports:
      - "80:80"

  django:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/srv/web:rw,cached
  db:
    image: postgres:14-alpine
    env_file:
      - 'docker/db/.env'
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  db-data: {}
  redis_data: {}
