version: '3.4'

services:
  nginx:
    ports:
      - "80:9000"

  django:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
      - rabbitmq
    command: "/bin/bash /srv/web/start.sh"
    volumes:
      - ./:/srv/web:rw,cached

  db:
    ports:
      - "5432:5432"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    ports:
      - "6379:6379"

volumes:
  db-data: { }
  redis_data: { }
