version: '3.4'

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/Dockerfile.nginx
    depends_on:
      - django
    volumes:
      - ./static:/srv/web/static:ro
    ports:
      - "80:9000"

  django:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/srv/web:rw,cached
  db:
    image: postgres:14-alpine
    env_file:
      - 'docker/db/.env'
    ports:
      - "5432:5432"
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  db-data: { }
  redis_data: { }
